import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createLocalDatabase} from '../scripts/dev-support.mjs';
import {createApp,hash,hmac,validateGuest} from '../server/core.mjs';
let db,rpc,day;
const next=(n)=>{const d=new Date(`${day}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);};
const token='a'.repeat(64),policy='Test cancellation policy: contact the property to arrange changes and refunds.';
before(async()=>{({db,rpc}=await createLocalDatabase());day=(await db.query("select ((now() at time zone 'Asia/Kolkata')::date)::text as today")).rows[0].today;
 await rpc('admin_settings',{booking_open:true,deposit_percent:50,cancellation_policy:policy,policy_reviewed:true,room_types:[{id:'deluxe',rate_paise:320000,max_guests:2},{id:'premium',rate_paise:380000,max_guests:2}]});});
after(()=>db.close());
async function openRoom(id,start,end){return rpc('admin_inventory',{room_ids:[id],start:next(start),end:next(end),is_open:true,note:''});}
async function hold(type,a,z,extra={}){const s={check_in:next(a),check_out:next(z),quantity:1,guests:2};const av=await rpc('availability',s);const r=av.rooms.find(r=>r.id===type);return rpc('hold',{...s,room_type:type,id:randomUUID(),reference:`TEST-${randomUUID()}`,request_key:randomUUID(),token_hash:hash(token),guest_name:'Test Guest',email:'guest@example.com',phone:'+919999999999',expected_total:r.total_paise,expected_deposit:r.deposit_paise,accepted_policy:policy,...extra});}
test('closed by default; open nights expose only available rooms',async()=>{let a=await rpc('availability',{check_in:next(1),check_out:next(2),quantity:1,guests:2});assert.equal(a.rooms[0].available,0);await openRoom('D1',1,1);a=await rpc('availability',{check_in:next(1),check_out:next(2),quantity:1,guests:2});assert.equal(a.rooms[0].available,1);});
test('a continuous stay needs the SAME physical room for every night',async()=>{await openRoom('D1',4,4);await openRoom('D2',5,5);const a=await rpc('availability',{check_in:next(4),check_out:next(6),quantity:1,guests:2});assert.equal(a.rooms[0].available,0);});
test('departure night is excluded and server computes seasonal price + advance',async()=>{await openRoom('D1',8,9);await rpc('admin_rates',{room_type:'deluxe',start:next(9),end:next(9),rate_paise:400000,reset:false});const b=await hold('deluxe',8,10);assert.equal(b.total_paise,720000);assert.equal(b.deposit_paise,360000);assert.equal(b.nightly_rates.length,2);});
test('two competing holds cannot sell the same room',async()=>{await openRoom('P1',12,12);const result=await Promise.allSettled([hold('premium',12,13),hold('premium',12,13)]);assert.equal(result.filter(r=>r.status==='fulfilled').length,1);assert.equal(result.filter(r=>r.status==='rejected').length,1);});
test('retries return original reservation; token must match',async()=>{await openRoom('D1',15,15);const key=randomUUID();const b=await hold('deluxe',15,16,{request_key:key});const b2=await hold('deluxe',15,16,{request_key:key});assert.equal(b.id,b2.id);await assert.rejects(()=>hold('deluxe',15,16,{request_key:key,token_hash:hash('wrong')}));});
test('stale or tampered quote cannot lower payment',async()=>{await openRoom('D1',17,17);await assert.rejects(()=>hold('deluxe',17,18,{expected_total:1}),{code:'QUOTE_CHANGED'});});
test('guest limit is enforced on server',async()=>{await openRoom('P1',19,19);await assert.rejects(()=>hold('premium',19,20,{guests:3}),{code:'INVALID_ROOM_OR_GUESTS'});});
test('cannot close inventory occupied by a payment hold',async()=>{await openRoom('P1',21,21);await hold('premium',21,22);await assert.rejects(()=>rpc('admin_inventory',{room_ids:['P1'],start:next(21),end:next(21),is_open:false}),{code:'RESERVATION_CONFLICT'});});
test('verified capture confirms only correct amount; duplicate is idempotent',async()=>{await openRoom('P1',23,23);let b=await hold('premium',23,24);const order=`order_${b.id}`;await rpc('attach_order',{id:b.id,order_id:order});await assert.rejects(()=>rpc('captured',{order_id:order,payment_id:'pay_test',amount:1,currency:'INR'}),{code:'PAYMENT_MISMATCH'});const capture={order_id:order,payment_id:'pay_test',amount:b.deposit_paise,currency:'INR'};b=await rpc('captured',capture);assert.equal(b.status,'confirmed');assert.equal((await rpc('captured',capture)).paid_paise,b.deposit_paise);});
test('expired hold releases stock; late payment after resale requires review',async()=>{await openRoom('P1',25,25);const first=await hold('premium',25,26);await rpc('attach_order',{id:first.id,order_id:'order_late'});await db.query("update ch_bookings set expires_at=now()-interval '1 minute' where id=$1",[first.id]);const second=await hold('premium',25,26);assert.notEqual(first.id,second.id);const b=await rpc('captured',{order_id:'order_late',payment_id:'pay_late',amount:first.deposit_paise,currency:'INR'});assert.equal(b.status,'payment_review');assert.equal(b.paid_paise,first.deposit_paise);});
test('refund + cancellation do not get reversed by duplicate capture',async()=>{const b=(await db.query("select * from ch_bookings where payment_id='pay_test'")).rows[0];await rpc('admin_cancel',{id:b.id});await rpc('refund',{id:b.id,payment_id:b.payment_id,amount_refunded:b.paid_paise});const again=await rpc('captured',{order_id:b.order_id,payment_id:b.payment_id,amount:b.paid_paise,currency:'INR'});assert.equal(again.status,'cancelled');assert.equal(again.refunded_paise,b.paid_paise);});
test('room order attach cannot be overwritten by a competing request',async()=>{await openRoom('D1',28,28);const b=await hold('deluxe',28,29);await rpc('attach_order',{id:b.id,order_id:'order_first'});const second=await rpc('attach_order',{id:b.id,order_id:'order_second'});assert.equal(second.order_id,'order_first');});
test('rate limiting persists counts',async()=>{assert.equal((await rpc('rate_limit',{key:'test',limit:1,seconds:60})).allowed,true);assert.equal((await rpc('rate_limit',{key:'test',limit:1,seconds:60})).allowed,false);});
test('anonymous database roles cannot read guests or call engine',async()=>{await db.exec('set role anon');await assert.rejects(()=>db.query('select * from ch_bookings'));await assert.rejects(()=>db.query("select ch_engine('admin_dashboard')"));await db.exec('reset role');});
test('admin authentication and origin validation are enforced',async()=>{const app=createApp({SITE_URL:'https://book.example.com'},{rpc});let r=await app(new Request('https://book.example.com/api/admin/dashboard'));assert.equal(r.status,401);r=await app(new Request('https://book.example.com/api/admin/inventory',{method:'POST',headers:{'content-type':'application/json',origin:'https://evil.example'},body:'{}'}));assert.equal(r.status,403);});
test('webhook verifies raw-body signature; production demo bypass unavailable',async()=>{const env={SITE_URL:'https://book.example.com',RAZORPAY_WEBHOOK_SECRET:'testsecret'};const app=createApp(env,{rpc});const raw=JSON.stringify({event:'unknown'});let r=await app(new Request('https://book.example.com/api/webhook',{method:'POST',body:raw,headers:{'x-razorpay-signature':'bad'}}));assert.equal(r.status,400);r=await app(new Request('https://book.example.com/api/webhook',{method:'POST',body:raw,headers:{'x-razorpay-signature':hmac(raw,'testsecret')}}));assert.equal(r.status,200);r=await app(new Request('https://book.example.com/api/checkout',{method:'POST',headers:{origin:'https://book.example.com','content-type':'application/json'},body:'{}'}));assert.equal(r.status,503);});
test('status API does not expose a reservation with the wrong token',async()=>{const b=(await db.query('select id from ch_bookings limit 1')).rows[0];const app=createApp({}, {rpc,demo:true});const r=await app(new Request('http://localhost/api/status',{method:'POST',headers:{origin:'http://localhost','content-type':'application/json'},body:JSON.stringify({id:b.id,token:'b'.repeat(64)})}));assert.equal(r.status,404);});
test('production verification rejects forged success and checks captured gateway data',async()=>{
 await openRoom('D1',31,31);let b=await hold('deluxe',31,32);await rpc('attach_order',{id:b.id,order_id:'order_api_verify'});
 let calls=0;const env={SITE_URL:'https://book.example.com',RATE_LIMIT_SECRET:'test-rate-secret',RAZORPAY_KEY_SECRET:'test-key-secret'};
 const app=createApp(env,{rpc,gateway:async()=>{calls++;return {id:'pay_api_verify',order_id:'order_api_verify',amount:b.deposit_paise,currency:'INR',status:'captured'};}});
 const payload={id:b.id,token,razorpay_order_id:'order_api_verify',razorpay_payment_id:'pay_api_verify',razorpay_signature:'forged'};
 const req=()=>new Request('https://book.example.com/api/verify',{method:'POST',headers:{origin:env.SITE_URL,'content-type':'application/json'},body:JSON.stringify(payload)});
 let r=await app(req(),{ip:'127.0.0.1'});assert.equal(r.status,400);assert.equal(calls,0);
 payload.razorpay_signature=hmac('order_api_verify|pay_api_verify',env.RAZORPAY_KEY_SECRET);
 r=await app(req(),{ip:'127.0.0.1'});assert.equal(r.status,200);assert.equal((await r.json()).booking.status,'confirmed');assert.equal(calls,1);
});
test('a valid non-owner auth account cannot obtain an admin session',async()=>{
 const env={SITE_URL:'https://book.example.com',ADMIN_EMAIL:'owner@example.com',RATE_LIMIT_SECRET:'test-limit'};
 const app=createApp(env,{rpc,auth:async()=>({user:{email:'someone@example.com',email_confirmed_at:'2026-01-01'},access_token:'not-owner',refresh_token:'not-owner'})});
 const r=await app(new Request('https://book.example.com/api/admin/login',{method:'POST',headers:{origin:env.SITE_URL,'content-type':'application/json'},body:JSON.stringify({email:'someone@example.com',password:'some-password'})}));
 assert.equal(r.status,401);assert.equal(r.headers.getSetCookie().length,0);
});
test('admin calendar returns six physical rooms and no guest access tokens',async()=>{
 const d=await rpc('admin_dashboard',{start:next(0)});assert.equal(d.rooms.length,6);assert.equal(d.calendar.length,84);assert.ok(d.bookings.every(b=>!('token_hash' in b)));
});
